#!/usr/bin/env python

import itertools
import os
import sys

import igc_lib
import lib.dumpers

items = os.listdir("C:/Users/bethge-adm/Documents/fredmaster/Tracks")

List_of_tracks = []
for names in items:
    if names.endswith(".igc"):
        List_of_tracks.append(names)
print List_of_tracks




def print_flight_details(flight):
    print "Flight:", flight
    print "Takeoff:", flight.takeoff_fix
    print"landingtime", flight.landing_fix
    print"thermals", flight.thermals

    print dir(flight)


def main():

    input_file = List_of_tracks
    #input_file = "C:/Users/bethge-adm/Documents/fredmaster/Tracks/2018-08-11_12.56_Disentis.igc"

    flight = igc_lib.Flight.create_from_file(input_file)

    print_flight_details(flight)



if __name__ == "__main__":
    main()
